#!/usr/bin/env bash

selected=$(find ~/github ~ -mindepth 1 -maxdepth 2 -type d | fzf \
    --exact \
    --bind "change:top" \
    --bind "shift-tab:up,tab:down" \
    --preview 'LS_COLORS=$(vivid generate one-dark); exa --color=auto --icons --long -h -a --git --no-permissions --no-user --time=accessed --group-directories-first {}')

    # --preview '(
    #     cd {} && 
    #     find . -maxdepth 1 -type d | sort | tail -n +2 | while read dir; do 
    #         echo -e "\033[1;34m${dir:2}/\033[0m"
    #     done &&
    #     find . -maxdepth 1 -type f | sort | while read file; do
    #         echo "${file:2}"
    #     done
    # )')

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
