# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

command_timeout = 3600

format = "$directory$all"

[character]
success_symbol = "[\\$>](green)"
error_symbol = "[\uead7](bold red)"

[package]
disabled = true

[git_branch]
symbol = ""
format = "[$symbol$branch(:$remote_branch)]($style) "

[directory]
truncate_to_repo = true

[ruby]
format = "[$symbol $version]($style) "
symbol = "[\ue791](red)"

[docker_context]
disabled = true
