# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

command_timeout = 3600

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[\ueab6](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[\uead7](bold red)" # The "error_symbol" segment is being set to "➜" with the color "bold red"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) is at "
disabled = false
show_always = true

[directory]
truncate_to_repo = true

[ruby]
format = "via [$symbol $version]($style) "
symbol = "[\ue791](red)"
