# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

command_timeout = 3600

# Format: ⟨user@hostname⟩ ~ ● (SSH) or ⟨hostname⟩ ~ ● (local)
format = "[⟨](base05)$username${hostname}[⟩](base05) $directory $character"

[character]
success_symbol = "[●](blue)"
error_symbol = "[●](red)"
format = "$symbol "

[package]
disabled = true

[hostname]
ssh_only = false
format = "[$hostname](base05)"
disabled = false

[directory]
truncate_to_repo = true
truncation_length = 100
format = "[$path](blue)"
home_symbol = "~"

[username]
format = "[$user@](base05)"
show_always = false
disabled = false
