# Catppuccin Mocha Theme
term_palette: 1e1e2e;f38ba8;a6e3a1;f9e2af;89b4fa;f5c2e7;94e2d5;cdd6f4
term_palette_bright: 585b70;f38ba8;a6e3a1;f9e2af;89b4fa;f5c2e7;94e2d5;cdd6f4
term_background: 1e1e2e
term_foreground: cdd6f4
term_background_bright: 585b70
term_foreground_bright: cdd6f4

# Hide branding for minimal look (optional - uncomment to enable)
# interface_branding:

interface_resolution: 1366x768

timeout: 5

/Arch Linux (linux)
    protocol: linux
    path: boot():/vmlinuz-linux
    cmdline: cryptdevice=PARTUUID=1cdb5e50-02:root root=/dev/mapper/root zswap.enabled=0 rw rootfstype=btrfs resume=/dev/mapper/root resume_offset=2106624
    module_path: boot():/initramfs-linux.img
    resolution: 1366x768

/Arch Linux (linux-fallback)
    protocol: linux
    path: boot():/vmlinuz-linux
    cmdline: cryptdevice=PARTUUID=1cdb5e50-02:root root=/dev/mapper/root zswap.enabled=0 rw rootfstype=btrfs resume=/dev/mapper/root resume_offset=2106624
    module_path: boot():/initramfs-linux-fallback.img
    resolution: 1366x768
