#!/usr/bin/env bash

# fzf to find relevant directories with all the eza options for previewing dir contents
selected=$(find -L ~/github ~ -mindepth 1 -maxdepth 2 -type d | sort -u | fzf \
    --cycle \
    --bind "change:top" \
    --bind "shift-tab:up,tab:down" \
    --preview 'eza --color=always --icons --classify --long -h -a --git --no-permissions --no-user --no-filesize --changed --git --group-directories-first {}')

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

init_tmux_session() {
    # If we're in a git worktree of any kind, whether bare or otherwise, start a new session and fire up some dev tools
    if git -C "$selected" rev-parse --is-inside-work-tree &>/dev/null; then
        create_selected_session
        create_dev_windows
        # Select first window
        tmux select-window -t "$selected_name":1
    else
        create_selected_session
    fi

    tmux attach -t "$selected_name"
}

# Create a new tmux session and use the selected dir as the working directory/the name for the session
create_selected_session() {
    tmux new-session -d -s "$selected_name" -c "$selected"
}

# Create new windows for nvim, shell, and lazygit
create_dev_windows() {
    # Create new window for nvim
    tmux send-keys -t "$selected_name" 'nvim' C-m

    # Create new window for shell
    tmux new-window -t "$selected_name" -c "$selected"

    # Create new window for lazygit
    tmux new-window -t "$selected_name" -c "$selected"
    tmux send-keys -t "$selected_name" 'lazygit' C-m
    
    # Create new window for claude (skip for LaTeX projects)
    if ! ls "$selected"/*.tex &>/dev/null; then
        tmux new-window -t "$selected_name" -c "$selected"
        tmux send-keys -t "$selected_name" 'claude' C-m
    fi
}

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    init_tmux_session
    exit 0
fi

# If the session doesn't exist, create it
if ! tmux has-session -t="$selected_name" 2> /dev/null; then
    init_tmux_session
fi

# If the session exists, switch to it
# This will still work if the session has already been created
tmux switch-client -t "$selected_name"
