#!/usr/bin/env bash

selected=$(find -L ~/github ~ -mindepth 1 -maxdepth 2 -type d | fzf \
    --bind "change:top" \
    --bind "shift-tab:up,tab:down" \
    --preview 'eza --color=always --icons --classify --long -h -a --git --no-permissions --no-user --no-filesize --changed --git --group-directories-first {}')

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

init_tmux_session() {
    if git -C "$selected" rev-parse --is-inside-work-tree &>/dev/null; then
        create_selected_session
        create_dev_windows
    else
        create_selected_session
    fi

    tmux attach -t $selected_name
}

create_selected_session() {
    tmux new-session -d -s $selected_name -c $selected
}

create_dev_windows() {
    tmux send-keys -t $selected_name 'nvim' C-m

    tmux new-window -t $selected_name -c $selected

    tmux new-window -t $selected_name -c $selected
    tmux send-keys -t $selected_name 'lazygit' C-m
}

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    init_tmux_session
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    init_tmux_session
fi

tmux switch-client -t $selected_name
